# Generated by Django 2.2.9 on 2020-01-27 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='N/A', max_length=64)),
                ('level', models.CharField(blank=True, default='N/A', max_length=64)),
                ('year', models.DateField(default=None, verbose_name='Graduation Year')),
            ],
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default=None, max_length=128)),
                ('job_title', models.CharField(default=None, max_length=64)),
                ('start_date', models.DateField(default=None, verbose_name='Employement Start Date')),
                ('end_date', models.DateField(default=None, verbose_name='Employement End Date')),
                ('leave_reason', models.CharField(default=None, max_length=512)),
                ('duties', models.ManyToManyField(related_name='duties', to='viewer.Duty')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('contact', models.CharField(blank=True, default='Availabe On Request', max_length=64)),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.Employment')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=64)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.Domain')),
            ],
        ),
        migrations.AddField(
            model_name='employment',
            name='projects',
            field=models.ManyToManyField(related_name='projects', to='viewer.Project'),
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=16)),
                ('education', models.ManyToManyField(blank=True, related_name='education', to='viewer.Education')),
                ('employment', models.ManyToManyField(blank=True, related_name='employments', to='viewer.Employment')),
                ('experiences', models.ManyToManyField(blank=True, related_name='domains', to='viewer.Experience')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reference', models.ManyToManyField(blank=True, related_name='references', to='viewer.Reference')),
            ],
        ),
    ]
