# Generated by Django 2.2.9 on 2020-01-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='exposure',
        ),
        migrations.AddField(
            model_name='employee',
            name='exposures',
            field=models.ManyToManyField(blank=True, related_name='exposures', to='viewer.TechField'),
        ),
        migrations.AlterField(
            model_name='tech',
            name='name',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
