# Generated by Django 2.2.9 on 2020-01-21 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duty',
            name='employment',
        ),
        migrations.RemoveField(
            model_name='project',
            name='employment',
        ),
        migrations.AddField(
            model_name='employment',
            name='duties',
            field=models.ManyToManyField(to='viewer.Duty'),
        ),
        migrations.AddField(
            model_name='employment',
            name='projects',
            field=models.ManyToManyField(to='viewer.Project'),
        ),
    ]
