# Generated by Django 2.2.9 on 2020-01-21 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_auto_20200121_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='exposures',
        ),
        migrations.AddField(
            model_name='employee',
            name='exposures',
            field=models.ForeignKey(blank=True, default='test', on_delete=django.db.models.deletion.CASCADE, related_name='exposures', to='viewer.TechField'),
            preserve_default=False,
        ),
    ]
