# Generated by Django 2.2.9 on 2020-01-21 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_auto_20200121_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='duties',
            field=models.ManyToManyField(related_name='duties', to='viewer.Duty'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='projects',
            field=models.ManyToManyField(related_name='projects', to='viewer.Project'),
        ),
    ]
