# Generated by Django 2.2.9 on 2020-01-21 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_auto_20200121_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tech',
            name='tech_field',
        ),
        migrations.AddField(
            model_name='tech',
            name='tech_field',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='viewer.TechField'),
            preserve_default=False,
        ),
    ]
