from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'resume'
urlpatterns = [
	path('', views.IndexView.as_view(), name="index"),
    path('html/<int:pk>', views.HTMLView.as_view(), name="html"),
    path('json/<int:pk>', views.JSONView.as_view(), name="json"),
    path('resume/', views.ResumeListView.as_view(), name="resumes"),
    path('resume/new/', views.new_resume, name="newResume"),
    path('resume/wizard', views.ResumeWizardView.as_view(), name="resumeWizard"),
    path('resume/edit/<int:pk>', views.ResumeUpdateView.as_view(), name='updateResume'),
    path('resume/delete/<int:pk>', views.ResumeDeleteView.as_view(), name='deleteResume'),
    path('applicant/', views.ApplicantListView.as_view(), name="applicants"),
    path('applicant/new', views.new_applicant, name="newApplicant"),
    path('applicant/edit/<int:pk>', views.ApplicantUpdateView.as_view(), name='updateApplicant'),
    path('applicant/delete/<int:pk>', views.ApplicantDeleteView.as_view(), name='deleteApplicant'),
    path('domain/', views.DomainListView.as_view(), name="domain"),
    path('domain/new', views.new_domain, name="newDomain"),
    path('domain/edit/<int:pk>', views.DomainUpdateView.as_view(), name='updateDomain'),
    path('domain/delete/<int:pk>', views.DomainDeleteView.as_view(), name='deleteDomain'),
    path('experience/', views.ExperienceListView.as_view(), name='xp'),
    path('experience/new', views.new_experience, name='newXP'),
    path('experience/edit/<int:pk>', views.ExperienceUpdateView.as_view(), name='updateXP'),
    path('experience/delete/<int:pk>', views.ExperienceDeleteView.as_view(), name='deleteXP'),
    path('education/', views.EducationListView.as_view(), name='edus'),
    path('education/new', views.new_education, name='newEDU'),
    path('education/edit/<int:pk>', views.EducationUpdateView.as_view(), name='updateEDU'),
    path('education/delete/<int:pk>', views.EducationDeleteView.as_view(), name='deleteEDU'),
    path('reference/', views.ReferenceListView.as_view(), name='refs'),
    path('reference/new', views.new_reference, name='newRef'),
    path('reference/edit/<int:pk>', views.ReferenceUpdateView.as_view(), name='updateRef'),
    path('reference/delete/<int:pk>', views.ReferenceDeleteView.as_view(), name='deleteRef'),
    path('employment/', views.EmploymentListView.as_view(), name='employments'),
    path('employment/new', views.new_employment, name='newEmploy'),
    path('employment/edit/<int:pk>', views.EmploymentUpdateView.as_view(), name='updateEmploy'),
    path('employment/delete/<int:pk>', views.EmploymentDeleteView.as_view(), name='deleteEmploy'),
    path('duty/', views.DutyListView.as_view(), name='duties'),
    path('duty/new', views.new_duty, name='newDuty'),
    path('duty/edit/<int:pk>', views.DutyUpdateView.as_view(), name='updateDuty'),
    path('duty/delete/<int:pk>', views.DutyDeleteView.as_view(), name='deleteDuty'),
    path('project/', views.ProjectListView.as_view(), name='projects'),
    path('project/new', views.new_project, name='newProject'),
    path('project/edit/<int:pk>', views.ProjectUpdateView.as_view(), name='updateProject'),
    path('project/delete/<int:pk>', views.ProjectDeleteView.as_view(), name='deleteProject'),
]